# Generated by Django 3.1.3 on 2020-11-18 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='days',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='seconds',
        ),
        migrations.AddField(
            model_name='discount',
            name='upto',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
